name: Git Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Folder
        run: mkdir files

      - name: Copy Files
        run: cp -r * files/
